### ISSUE TITLE
multiple push button

### ISSUE THREAD

**Issue by nalakawula** [MajicDesigns/MD_UISwitch#1]
I have 10 push button? Any example how to use your library to use with multiple button? thanks

**Comment by MajicDesigns** [comment]
That depends on what you need to do. If you want to be able to select more than 1 at a time, then you declare 10 switch objects. If only one is active at a time, you can declare an array of PIN numbers and the library will manage that as well.  Combination of the two is also possible. Examples in the library should show how each is done and also read the documentation for the library.
