### ISSUE TITLE
Version 2.0 is not backward compatible with 1.2.x

### ISSUE THREAD

**Issue by alf45tar** [MajicDesigns/MD_UISwitch#9]
I using your fantastic library for my PedalinoMini project but with the latest version 2.0 nothing is working ad before. Most of the time press is not reported or block the execution.
PedalinoMini is working on ESP32 board with Arduino framework.

Thanks
alf45tar

**Comment by MajicDesigns** [comment]
I have tested the library before release and, aside from the KEY_DOWN and KEY_UP that are new, the notifications of the other key states is substantially identical to the previous version.

Can you please try the  UI_Switch_Example code and test whether you see the same non functioning with that code - it is very simplified code that just simply prints out what key type has been pressed.

**Comment by alf45tar** [comment]
UI_Switch_Example works like a charm
I will check better my code

**Comment by MajicDesigns** [comment]
Ok, Let me know if you need more info.
